# Generated by Django 5.0.7 on 2024-08-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название произведения')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Фото')),
                ('audio', models.FileField(upload_to='audios/', verbose_name='Аудио файл (MP3)')),
                ('description', models.TextField(verbose_name='Описание произведения')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
        ),
    ]
